### ISSUE TITLE
rgtk project

### ISSUE THREAD

**Issue by GuillaumeGomez** [cyderize/cairo-rs#1]
Hi,

A friend and me are actually binding the gnome libraries, including cairo in the [rgtk project](https://github.com/jeremyletang/rgtk). We already have started it (and it's in an advanced stage right now). Wouldn't you prefer to contribute on our own by following our widget design ?

**Comment by cyderize** [comment]
Ah, I wasn't aware of these bindings.

To be honest, this library is mainly for me to get more familiar with Rust FFI, so I'll likely continue on it (albeit slowly).

I'll certainly contribute to rgtk if I can, it looks great!

**Comment by GuillaumeGomez** [comment]
No problem ! It would be great if you could since cairo is one of the less binded libraries.We have finished gdk, almost gtk, glib is well advanced and I started pango recently. We were speaking about creating an organization for that. I think it'll come in the next months. If you need help on rust or something, don't hesitate to ask me questions !
